### ISSUE TITLE
[Feature request] Separate Colors config option | The ability to move the indicator around

### ISSUE THREAD

**Issue by ryktear** [ever39/LocalFlashlight#1]
First I'd like to say this is a nice mod!

I'd like to request two things if possible:

- I'd like to be able to use a green color for the indicator and keep flashlight color white, but currently the config sets both to the same color.
- I'd also like to able to customize the location of the indicator (if possible and not too complicated).

Looking forward to future updates for this mod!

**Comment by PouriaRe** [comment]
bro, can you tell me how to config the mod? haven't been able to figure that out. I read the code but there is no file for config and I cant seem to find a button to enable confige ui.

**Comment by ryktear** [comment]
Features added as of V1.2

Thank you! Closing this request now!
