### ISSUE TITLE
reserved slots compatibility

### ISSUE THREAD

**Issue by ElettroGame04** [ever39/LocalFlashlight#10]
when using the reserved flashlight slot mod, when i pick up a flashlight with the reserved slot enabled and drop it, i still can't use the localflashlight, even if the flashlight is not in my inventory anymore. it would be good if when the flashlight is dropped and not in the inventory i could use the local one again, without having to die, change moon or reopen the lobby.

**Comment by ever39** [comment]
will try fixing it, but for now you can disable the config if you don't have any mods that have the same keybinds as localflashlight

**Comment by ElettroGame04** [comment]
thanks, for now i'll do that, still hope you can fix it though

**Comment by ever39** [comment]
i forgot to say that this was added in v1.5, thanks for the feature request though
