### ISSUE TITLE
Time mode Reloading sound

### ISSUE THREAD

**Issue by Xeraccoon** [ever39/LocalFlashlight#12]
Hello, I wonder if something can be done for the reloading sound because in Time mode, as soon as we use a little lamp and it is fully recharged we have this famous reloading sound and suddenly we have it hears a lot so I wonder if it is possible to remove this sound for this use case, or else it would be necessary to block the lamp at 99% to avoid this noise (in Time mode)

**Comment by ever39** [comment]
the sound doesn't seem to be breaking for me but i did find that the config related to the recharge sound being on or off didn't work so it should be fixed in a small little update that i'll release soon (hopefully)

**Comment by ever39** [comment]
fixed in v1.5.1, thanks for the bug report (and also for the other one)
