### ISSUE TITLE
how do you config the mod?

### ISSUE THREAD

**Issue by PouriaRe** [ever39/LocalFlashlight#2]
It's not explained anywhere how we can configure the mod. the flashlight runs out very quickly. please add a how-to-use for the mod in the readme file. Great mod btw.

**Comment by ever39** [comment]
the mod makes a config file when you start up the game after installing it which has all the configs (which you can change in the config editor if you're using thunderstore mod manager or r2modman, or you can open the command.localFlashlight.cfg file in BepInEx/config) but i'll also add a section for mod configuration in the readme file

**Comment by PouriaRe** [comment]
thank you so much. didn't realize the file was generated after running the game. writing this in the readme file is a good idea.
