### ISSUE TITLE
 [Feature request] Different sound option

### ISSUE THREAD

**Issue by EchoLWS999** [ever39/LocalFlashlight#3]
I love this mod but cannot stand the high pitched sound the flashlight makes, could you make some configurable options, including a normal sounding one?

**Comment by ever39** [comment]
so making an option where the flashlight sounds like the normal in-game flashlight, or just like a normal flashlight in general?

**Comment by EchoLWS999** [comment]
> so making an option where the flashlight sounds like the normal in-game flashlight, or just like a normal flashlight in general?

Both or if it's one or the other probably the one in game for consistency

**Comment by ever39** [comment]
alright, i'll add the in-game sounds too next update then

**Comment by EchoLWS999** [comment]
> alright, i'll add the in-game sounds too next update then

Thank you so much!
