### ISSUE TITLE
Flashlight stops working after death.

### ISSUE THREAD

**Issue by MrBl4ckSkull** [ever39/LocalFlashlight#4]
The flashlight doesn't work anymore after death; I have no other mods installed and the default config settings. I am unsure if it is relevant, that the flashlight was on when I died.

When I try to turn the flashlight on, the battery still drains, but there is no sound that plays to indicate the flashlight has switched on (and obviously, the light does not turn on).

**Comment by ever39** [comment]
yeah it was an issue of turning off the gameobject when the player dies and never turning it back on, just fixed it after i experienced it myself, sorry
