### ISSUE TITLE
[Feature request] See other players' flashlights, and compatibility with flashlight toggle mods.

### ISSUE THREAD

**Issue by MrBl4ckSkull** [ever39/LocalFlashlight#5]
When another player turns on their flashlight, you cannot see their light beam, it would be nice if you could see it.

Additionally, when ReservedFlashlightSlot is installed and you have a flashlight, the default toggle flashlight key is F (like with the local flashlight) meaning the two flashlights "overlap". It would be nice if the flashlight/pro-flashlight was prioritized, and if the flashlight is on then the local flashlight cannot switch on (to prevent the toggle sound of the light, and draining your local battery). I have not tested this with FlashlightToggle when you have a flashlight in your inventory, but I imagine similar functionality would need to be added, too.

**Comment by ever39** [comment]
added the functionality of the second request, although i probably should remove the deny sound that it makes when attempting to toggle while having either a helmetlight enabled or a flashlight equipped, the first request though.. i'm not really good at networking but i could probably try adding something like that, not sure how to keep it client-sided with networking enabled though
small edit: i'll probably keep the deny sound cause its kinda like a heads up about the player holding a flashlight already

**Comment by PouriaRe** [comment]
I prefer this being only client-sided. I don't want other people to know that I'm using this mod. Also, I want my configurations to be my own. not the host's.

**Comment by ever39** [comment]
bad news related to this, i dont think i can implement any sort of networking without ruining vanilla player compatibility, and i can't make it so theres an option for them to sort of "see" your light as if you were using a bbflashlight or a pro-flashlight unless you're the host, so i'll probably implement the seeing other flashlights thing, however it might need everybody to have the mod

**Comment by ever39** [comment]
networking implemented (properly) in v1.4.12, so this issue is completed
same goes with the compatibility with flashlight toggle mods (at least in vanilla, still need to fix it when using reserved slots)
