### ISSUE TITLE
I tried joining a LAN game, but the game freezes.

### ISSUE THREAD

**Issue by Friskzips** [ever39/LocalFlashlight#7]
I was testing some stuff with LAN mode. 
but when I was entering the lobby with the client, the game frozen and a lot of errors appeared in the terminal.
I am going to reproduce it because it didn't give me the log.
![localFlashlightCrash](https://github.com/ever39/LocalFlashlight/assets/99197717/683a4c8a-a1f9-4693-91af-9f55abe5b675)

**Comment by ever39** [comment]
what mods were you using? so far i've only gotten a report about the fact that LC_Office and CozyOffice cause the issue to happen, so it might be because of those mods, but if it isn't from those mods then if you could send the modlist that you're using it would help a lot to find the error

**Comment by Friskzips** [comment]
Crash log
[LogOutput.log](https://github.com/ever39/LocalFlashlight/files/15203013/LogOutput.log)
Mods(there is cozy office but it isnt listed)
[Mods.log](https://github.com/ever39/LocalFlashlight/files/15203020/Mods.log)

**Comment by Friskzips** [comment]
i am gonna try 
without cozy office

**Comment by ever39** [comment]
yeah i think cozy office might cause the issue, no idea since i also had plenty of issues with that mod while testing(and even after testing, somehow)
